# Generated by Django 2.2.1 on 2020-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_tracker', '0003_exclude_login_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='键')),
                ('value', models.BooleanField(default=False, verbose_name='值')),
            ],
        ),
        migrations.AlterField(
            model_name='exclude',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'equal'), (1, 'basic-re'), (2, 'extended-re')], default=0),
        ),
        migrations.AlterField(
            model_name='exclude',
            name='column',
            field=models.PositiveSmallIntegerField(choices=[(0, 'api_uid'), (10, 'method'), (100, 'url:scheme'), (101, 'url:netloc'), (102, 'url:path'), (103, 'url:query'), (104, 'url:fragment')]),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'equal'), (1, 'basic-re'), (2, 'extended-re')], default=0),
        ),
        migrations.AlterField(
            model_name='filter',
            name='column',
            field=models.PositiveSmallIntegerField(choices=[(0, 'api_uid'), (10, 'method'), (100, 'url:scheme'), (101, 'url:netloc'), (102, 'url:path'), (103, 'url:query'), (104, 'url:fragment')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='api_uid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PUT', 'PUT')], default='GET', max_length=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CREATED', 'CREATED'), ('SUCCESS', 'SUCCESS')], default='CREATED', max_length=16),
        ),
    ]
