# Generated by Django 2.2.6 on 2021-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_tracker', '0005_initial_config_is_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='method',
            field=models.CharField(choices=[('PATCH', 'PATCH'), ('GET', 'GET'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('POST', 'POST'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=8),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS'), ('CREATED', 'CREATED'), ('FAILURE', 'FAILURE')], default='CREATED', max_length=16),
        ),
    ]
