export default {
  nav: {
    head: 'head_ol',
    side: 'side_menu',
  },
  common: {
    biz: 'select_biz',
    headCheck: 'checkbox_tableCheckAll',
    headCheckUl: 'ul_tableCheckAll',
    headSet: 'btn_tableColSet',
    headSetPanel: 'panel_tableColSet',
    installTable: 'table_install',
    formCommit: 'btn_commit',
    formReset: 'btn_reset',
    installMethod: 'form_installSwitch',
    more: 'btn_singleMore',
    stepPrev: 'btn_stepPrev',
    stepNext: 'btn_stepNext',
    fileInput: 'input_fileInput',
    versionForm: 'form_versionForm',
    more: 'btn_more',
    moreItem: 'btn_moreItem',
    iconMore: 'icon_more',
  },
  // route.name
  agentStatus: {
    install: 'btn_install',
    installUl: 'ul_install',
    copy: 'btn_copy',
    operate: 'btn_operate',
    bizTopo: 'select_bizTopo',
    search: 'select_search',
    reload: 'btn_singleReload',
  },
  agentSetup: {
    setupWrapper: 'wrapper_setup',
    formSetup: 'form_setup',
  },
  agentImport: {
    importForm: 'form_importForm',
    formImport: 'btn_importExcel',
    excelUpload: 'wrapper_excel',
    excelInput: 'input_excel',
  },
  plugin: {
    pluginList: 'wrapper_pluginList',
    listTable: 'table_listTable',
    listTable: 'table_list',
    rowSelect: 'select_row',
    showDetail: 'btn_showHost',
    operate: 'btn_operatePlugin',
    copy: 'btn_copyHostIp',
    strategy: 'select_strategyFilter',
    searchSelect: 'select_search',
    operateForm: 'form_batchOperate',
    pluginName: 'select_pluginName',
    MAIN_INSTALL_PLUGIN: 'btn_install',
    MAIN_START_PLUGIN: 'btn_start',
    MAIN_STOP_PLUGIN: 'btn_stop',
    MAIN_RESTART_PLUGIN: 'btn_restart',
    MAIN_RELOAD_PLUGIN: 'btn_reload',
    MAIN_DELEGATE_PLUGIN: 'btn_delegate',
    MAIN_UNDELEGATE_PLUGIN: 'btn_undelegate',
  },
  pluginRule: {
    policy: 'wrapper_policy',
    addPolicy: 'btn_addPolicy',
    searchInput: 'input_search',
    policyTable: 'table_policy',
    filterNode: 'btn_filterNode',
    start: 'btn_start',
    edit: 'btn_edit',
    stop: 'btn_stop',
    delete: 'btn_delete',
    stopAndDelete: 'btn_stopAndDelete',
    createGray: 'btn_createGray',
    editGray: 'btn_editGray',
    releaseGray: 'btn_releaseGray',
    deleteGray: 'btn_deleteGray',
    stopPolicy: 'radio_stopPolicy',
    stopPlugin: 'radio_stopPlugin',
  },
  policy: {
    chooseForm: 'form_choose',
    oldRule: 'radio_oldPolicy',
    newRule: 'radio_newPolicy',
    policyTable: 'table_policyTable',
    policyRadio: 'radio_policyRadio',
    policyProcess: 'wrapper_policyProcess',
    policyStep: 'tab_policyStep',
    targetForm: 'form_targetForm',
    name: 'input_policyName',
    ipSelect: 'select_ipSelect',
    versionForm: 'form_curVersion',
    curVersionTable: 'table_curVersion',
    chooseVersionTable: 'table_chooseVersion',
    versionRadio: 'radio_chooseVersion',
    policyParams: 'wrapper_params',
    collapseItem: 'collapse_item',
    preview: 'wrapper_preview',
    previewTable: 'table_preview',
    tableTab: 'tab_tableHead',
    deleteBtn: 'btn_delete',
    deletePopBtn: 'btn_popDelete',
  },
  pluginDetail: {
    pluginDetail: 'wrapper_pluginDetail',
    ready: 'btn_readyPlugin',
    versionManage: 'btm_versionManage',
    pluginDetail: 'wrapper_pluginDetail',
    statusChange: 'btn_statusChange',
    statusUL: 'ul_statusUL',
  },
  pluginPackage: {
    package: 'wrapper_package',
    import: 'btn_import',
    search: 'input_search',
    viewPlugin: 'btn_viewPlugin',
    filterNode: 'btn_filterNode',
    goDeploy: 'btn_goDeploy',
  },
  cloudManager: {
    cloudManager: 'wrapper_cloud',
    addCloud: 'btn_addCloud',
    copyProxy: 'btn_copyProxy',
    searchCloud: 'input_searchCloud',
    cloudTable: 'table_cloudTable',
    viewDetail: 'btn_viewDetail',
    filterAgent: 'btn_filterAgent',
    instalProxy: 'btn_instalProxy',
    editCloud: 'btn_editCloud',
    deleteCloud: 'btn_deleteCloud',
  },
  cloudInfo: {
    cloudInfo: 'wrapper_cloudInfo',
    cloudForm: 'form_cloudInfo',
    cloudName: 'input_cloudName',
    cloudIsp: 'select_cloudIsp',
    cloudAp: 'btn_cloudAp',
  },
  cloudManagerDetail: {
    cloudNav: 'wrapper_cloudNav',
    cloudItem: 'nav_cloudItem',
    cloudFilter: 'input_cloudFilter',
    cloudFilter: 'input_cloudFilter',
    cloudFilter: 'input_cloudFilter',
    cloudFilter: 'input_cloudFilter',
    cloudFilter: 'input_cloudFilter',
    proxyTable: 'table_proxy',
    install: 'btn_installProxy',
    copy: 'btn_copyProxy',
    view: 'btn_viewProxy',
    reinstall: 'btn_reinstallProxy',
    edit: 'btn_editProxy',
    copyProxy: 'btn_copyProxy',
    proxyForm: 'form_proxyForm',
    channelItem: 'tab_channelItem',
    addChannel: 'btn_addChannel',
    editChannel: 'btn_editChannel',
    deleteChannel: 'btn_deleteChannel',
    channelForm: 'form_channelForm',
    formItem: 'input_formItem',
  },
  taskList: {
    history: 'wrapper_history',
    toggleDeploy: 'checkbox_deploy',
    datePicker: 'picker_data',
    searchSelect: 'select_search',
  },
  taskDetail: {
    taskDetail: 'wrapper_taskDetail',
    copy: 'btn_copy',
    stop: 'btn_stop',
    retry: 'btn_retry',
    filter: 'select_filter',
    detailTable: 'table_detail',
    singleRetry: 'btn_singleRetry',
    singleRetry: 'btn_singleRetry',
    log: 'btn_viewLog',
  },
  taskLog: {
    taskLog: 'wrapper_taskLog',
    hostSearch: 'input_hostSearch',
    hostList: 'ul_hostList',
    stop: 'btn_stop',
    retry: 'btn_retry',
    download: 'btn_downloadLog',
  },
  gseConfig: {
    configWrapper: 'wrapper_gseConfig',
    addAp: 'btn_addAp',
    editAp: 'btn_editAp',
    deleteAp: 'btn_deleteAp',
  },
  accessPoint: {
    apBaseForm: 'form_apBase',
    apBaseTable: 'table_apBase',
    apTestBtn: 'btn_apTest',
    apBaseInput: 'input_apBase',
    addRowBtn: 'btn_addRow',
    deleteRowBtn: 'btn_deleteRow',
    apHostInput: 'input_apHost',
    apHostPackage: 'input_package',
    addPackageBtn: 'btn_addPackage',
    deletePackageBtn: 'btn_deletePackage',
  },
};
