# Generated by Django 2.2.8 on 2021-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0025_repair_windows_run_and_pid_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="outer_callback_url",
            field=models.CharField(blank=True, default="", max_length=128, null=True, verbose_name="节点管理外网回调地址"),
        ),
    ]
