# Generated by Django 2.2.8 on 2021-08-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0026_accesspoint_outer_callback_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="os_type",
            field=models.CharField(
                choices=[("LINUX", "LINUX"), ("WINDOWS", "WINDOWS"), ("AIX", "AIX"), ("SOLARIS", "SOLARIS")],
                db_index=True,
                default="LINUX",
                max_length=45,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="cpu_arch",
            field=models.CharField(
                choices=[
                    ("x86", "x86"),
                    ("x86_64", "x86_64"),
                    ("powerpc", "powerpc"),
                    ("aarch64", "aarch64"),
                    ("sparc", "sparc"),
                ],
                db_index=True,
                default="x86_64",
                max_length=32,
                verbose_name="CPU类型",
            ),
        ),
        migrations.AlterField(
            model_name="pushfilerecord",
            name="os_type",
            field=models.CharField(
                choices=[("LINUX", "LINUX"), ("WINDOWS", "WINDOWS"), ("AIX", "AIX"), ("SOLARIS", "SOLARIS")],
                db_index=True,
                default="LINUX",
                max_length=45,
                verbose_name="操作系统",
            ),
        ),
    ]
