# Generated by Django 2.2.8 on 2021-08-04 04:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0026_accesspoint_outer_callback_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallChannel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=45, verbose_name="名称")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("jump_servers", django_mysql.models.JSONField(default=dict, verbose_name="安装通道跳板机")),
                ("upstream_servers", django_mysql.models.JSONField(default=dict, verbose_name="上游节点")),
            ],
            options={
                "verbose_name": "安装通道",
                "verbose_name_plural": "安装通道",
            },
        ),
        migrations.AddField(
            model_name="host",
            name="install_channel_id",
            field=models.IntegerField(null=True, verbose_name="安装通道"),
        ),
    ]
