# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-节点管理(BlueKing-BK-NODEMAN) available.
Copyright (C) 2017-2022 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.8 on 2021-02-08 09:52

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0027_merge_20210108_1546"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSubscriptionInstanceMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_instance_id", models.BigIntegerField(db_index=True, verbose_name="作业实例ID")),
                ("subscription_instance_ids", django_mysql.models.JSONField(default=list, verbose_name="订阅实例ID列表")),
                ("node_id", models.CharField(db_index=True, max_length=32, verbose_name="节点ID")),
                (
                    "status",
                    models.CharField(
                        default=1,
                        max_length=45,
                        verbose_name="作业状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业平台ID映射表",
                "verbose_name_plural": "作业平台ID映射表",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInstanceLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription_instance_record_id", models.BigIntegerField(db_index=True, verbose_name="订阅实例ID")),
                ("log", models.TextField(verbose_name="日志内容")),
                ("level_name", models.SlugField(max_length=32, verbose_name="日志等级")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "作业平台ID映射表",
                "verbose_name_plural": "作业平台ID映射表",
            },
        ),
        migrations.AddField(
            model_name="host",
            name="cpu_arch",
            field=models.CharField(
                choices=[("x86", "x86"), ("x86_64", "x86_64"), ("powerpc", "powerpc"), ("aarch64", "aarch64")],
                db_index=True,
                default="x86_64",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="node_type",
            field=models.CharField(
                choices=[("AGENT", "AGENT"), ("PROXY", "PROXY"), ("PAGENT", "PAGENT")],
                db_index=True,
                max_length=16,
                verbose_name="节点类型",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="os_type",
            field=models.CharField(
                choices=[("LINUX", "LINUX"), ("WINDOWS", "WINDOWS"), ("AIX", "AIX")],
                db_index=True,
                default="LINUX",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("INSTALL_AGENT", "INSTALL_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("REINSTALL_AGENT", "REINSTALL_AGENT"),
                    ("UNINSTALL_AGENT", "UNINSTALL_AGENT"),
                    ("REMOVE_AGENT", "REMOVE_AGENT"),
                    ("UPGRADE_PROXY", "UPGRADE_PROXY"),
                    ("UPGRADE_AGENT", "UPGRADE_AGENT"),
                    ("IMPORT_AGENT", "IMPORT_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("RELOAD_AGENT", "RELOAD_AGENT"),
                    ("MAIN_START_PLUGIN", "MAIN_START_PLUGIN"),
                    ("MAIN_STOP_PLUGIN", "MAIN_STOP_PLUGIN"),
                    ("MAIN_RESTART_PLUGIN", "MAIN_RESTART_PLUGIN"),
                    ("MAIN_RELOAD_PLUGIN", "MAIN_RELOAD_PLUGIN"),
                    ("MAIN_DELEGATE_PLUGIN", "MAIN_DELEGATE_PLUGIN"),
                    ("MAIN_UNDELEGATE_PLUGIN", "MAIN_UNDELEGATE_PLUGIN"),
                    ("MAIN_INSTALL_PLUGIN", "MAIN_INSTALL_PLUGIN"),
                    ("UPDATE_AUTHINFO", "UPDATE_AUTHINFO"),
                    ("PACKING_PLUGIN", "PACKING_PLUGIN"),
                    ("INSTALL_PROXY", "INSTALL_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("REINSTALL_PROXY", "REINSTALL_PROXY"),
                    ("REPLACE_PROXY", "REPLACE_PROXY"),
                    ("UNINSTALL_PROXY", "UNINSTALL_PROXY"),
                    ("UPGRADE_PROXY", "UPGRADE_PROXY"),
                    ("IMPORT_PROXY", "IMPORT_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("RELOAD_PROXY", "RELOAD_PROXY"),
                ],
                default="INSTALL_PROXY",
                max_length=45,
                verbose_name="作业类型",
            ),
        ),
    ]
