# Generated by Django 2.2.8 on 2021-07-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0045_auto_20210608_1623"),
        ("node_man", "0026_accesspoint_outer_callback_url"),
    ]

    operations = []
