# Generated by Django 2.2.6 on 2021-07-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0046_merge_20210719_1607"),
        ("node_man", "0047_auto_20210707_1201"),
    ]

    operations = []
