# Generated by Django 2.2.6 on 2021-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0051_auto_20210903_1320"),
        ("node_man", "0052_update_gse_config"),
    ]

    operations = []
