# Generated by Django 2.2.6 on 2021-09-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0053_merge_20210910_1624"),
        ("node_man", "0027_auto_20210803_1421"),
    ]

    operations = []
