# Generated by Django 3.2.9 on 2022-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0056_pluginresourcepolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginconfigtemplate",
            name="cpu_arch",
            field=models.CharField(
                choices=[
                    ("x86", "x86"),
                    ("x86_64", "x86_64"),
                    ("powerpc", "powerpc"),
                    ("aarch64", "aarch64"),
                    ("sparc", "sparc"),
                ],
                default="x86_64",
                max_length=16,
                verbose_name="CPU架构",
            ),
        ),
        migrations.AddField(
            model_name="pluginconfigtemplate",
            name="os",
            field=models.CharField(
                choices=[("windows", "windows"), ("linux", "linux"), ("aix", "aix")],
                default="linux",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pluginconfigtemplate",
            unique_together={("plugin_name", "plugin_version", "name", "version", "is_main", "os", "cpu_arch")},
        ),
    ]
