# Generated by Django 3.2.4 on 2022-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0058_replenish_plugin_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="bk_agent_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="AgentID"),
        ),
        migrations.AlterField(
            model_name="host",
            name="cpu_arch",
            field=models.CharField(
                choices=[
                    ("x86", "x86"),
                    ("x86_64", "x86_64"),
                    ("powerpc", "powerpc"),
                    ("aarch64", "aarch64"),
                    ("sparc", "sparc"),
                ],
                db_index=True,
                default="x86_64",
                max_length=16,
                verbose_name="CPU架构",
            ),
        ),
    ]
