# Generated by Django 3.2.4 on 2022-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0058_replenish_plugin_template"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="PushFileRecord",
        ),
        migrations.AlterModelOptions(
            name="accesspoint",
            options={"verbose_name": "接入点（AccessPoint）", "verbose_name_plural": "接入点（AccessPoint）"},
        ),
        migrations.AlterModelOptions(
            name="cloud",
            options={"verbose_name": "云区域（Cloud）", "verbose_name_plural": "云区域（Cloud）"},
        ),
        migrations.AlterModelOptions(
            name="cmdbeventrecord",
            options={"verbose_name": "CMDB事件记录", "verbose_name_plural": "CMDB事件记录"},
        ),
        migrations.AlterModelOptions(
            name="downloadrecord",
            options={"verbose_name": "下载记录", "verbose_name_plural": "下载记录"},
        ),
        migrations.AlterModelOptions(
            name="globalsettings",
            options={"verbose_name": "配置表（GlobalSettings）", "verbose_name_plural": "配置表（GlobalSettings）"},
        ),
        migrations.AlterModelOptions(
            name="gseplugindesc",
            options={"verbose_name": "插件信息（GsePluginDesc）", "verbose_name_plural": "插件信息（GsePluginDesc）"},
        ),
        migrations.AlterModelOptions(
            name="host",
            options={
                "ordering": ["-updated_at", "-bk_host_id"],
                "verbose_name": "主机（Host）",
                "verbose_name_plural": "主机（Host）",
            },
        ),
        migrations.AlterModelOptions(
            name="identitydata",
            options={"verbose_name": "临时认证数据（IdentityData）", "verbose_name_plural": "临时认证数据（IdentityData）"},
        ),
        migrations.AlterModelOptions(
            name="installchannel",
            options={"verbose_name": "安装通道（InstallChannel）", "verbose_name_plural": "安装通道（InstallChannel）"},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-id"], "verbose_name": "任务信息（Job）", "verbose_name_plural": "任务信息（Job）"},
        ),
        migrations.AlterModelOptions(
            name="jobtask",
            options={"verbose_name": "任务详情（JobTask）", "verbose_name_plural": "任务详情（JobTask）"},
        ),
        migrations.AlterModelOptions(
            name="packages",
            options={"verbose_name": "插件包（Packages）", "verbose_name_plural": "插件包（Packages）"},
        ),
        migrations.AlterModelOptions(
            name="proccontrol",
            options={"verbose_name": "插件控制表（ProcControl）", "verbose_name_plural": "插件控制表（ProcControl）"},
        ),
        migrations.AlterModelOptions(
            name="processstatus",
            options={"verbose_name": "进程状态（ProcessStatus）", "verbose_name_plural": "进程状态（ProcessStatus）"},
        ),
        migrations.AlterModelOptions(
            name="resourcewatchevent",
            options={"verbose_name": "CMDB资源监听事件", "verbose_name_plural": "CMDB资源监听事件"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "订阅（Subscription）", "verbose_name_plural": "订阅（Subscription）"},
        ),
        migrations.AlterModelOptions(
            name="subscriptioninstancelog",
            options={"verbose_name": "订阅实例日志", "verbose_name_plural": "订阅实例日志"},
        ),
        migrations.AlterModelOptions(
            name="subscriptioninstancerecord",
            options={"verbose_name": "订阅实例记录", "verbose_name_plural": "订阅实例记录"},
        ),
        migrations.AlterModelOptions(
            name="subscriptionstep",
            options={"ordering": ["index"], "verbose_name": "订阅步骤", "verbose_name_plural": "订阅步骤"},
        ),
        migrations.AlterModelOptions(
            name="subscriptiontask",
            options={"ordering": ["-create_time"], "verbose_name": "订阅任务", "verbose_name_plural": "订阅任务"},
        ),
        migrations.AddField(
            model_name="pluginconfigtemplate",
            name="variables",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="配置变量"),
        ),
    ]
