# Generated by Django 3.2.4 on 2022-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0059_auto_20220315_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="inner_ipv6",
            field=models.CharField(blank=True, default="", max_length=45, null=True, verbose_name="内网IPv6"),
        ),
        migrations.AddField(
            model_name="host",
            name="outer_ipv6",
            field=models.CharField(blank=True, default="", max_length=45, null=True, verbose_name="外网IPv6"),
        ),
        migrations.AlterField(
            model_name="host",
            name="data_ip",
            field=models.CharField(blank=True, default="", max_length=15, null=True, verbose_name="数据IP"),
        ),
        migrations.AlterField(
            model_name="host",
            name="inner_ip",
            field=models.CharField(db_index=True, max_length=15, verbose_name="内网IP"),
        ),
        migrations.AlterField(
            model_name="host",
            name="login_ip",
            field=models.CharField(blank=True, default="", max_length=15, null=True, verbose_name="登录IP"),
        ),
        migrations.AlterField(
            model_name="host",
            name="outer_ip",
            field=models.CharField(blank=True, default="", max_length=15, null=True, verbose_name="外网IP"),
        ),
    ]
