# Generated by Django 3.2.4 on 2022-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0059_auto_20220415_2150"),
        ("node_man", "0060_auto_20220315_2044"),
    ]

    operations = []
