# Generated by Django 3.2.4 on 2022-06-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0061_merge_0059_auto_20220415_2150_0060_auto_20220315_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="bk_addressing",
            field=models.CharField(default="0", max_length=16, verbose_name="寻地方式"),
        ),
        migrations.AlterField(
            model_name="host",
            name="data_ip",
            field=models.CharField(blank=True, default="", max_length=45, null=True, verbose_name="数据IP"),
        ),
        migrations.AlterField(
            model_name="host",
            name="login_ip",
            field=models.CharField(blank=True, default="", max_length=45, null=True, verbose_name="登录IP"),
        ),
    ]
