# Generated by Django 3.2.4 on 2022-07-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0060_host_os_version"),
        ("node_man", "0062_auto_20220620_1150"),
    ]

    operations = []
