# Generated by Django 3.2.4 on 2022-07-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0063_merge_0060_host_os_version_0062_auto_20220620_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="bk_host_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128, null=True, verbose_name="主机名称"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioninstancerecord",
            name="instance_id",
            field=models.CharField(db_index=True, max_length=128, verbose_name="实例ID"),
        ),
    ]
