# Generated by Django 3.2.4 on 2022-08-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0064_auto_20220721_1557"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscriptionstep",
            unique_together={("subscription_id", "step_id")},
        ),
    ]
