# Generated by Django 3.2.4 on 2022-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0065_alter_subscriptionstep_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="os",
            field=models.CharField(
                choices=[("windows", "windows"), ("linux", "linux"), ("aix", "aix"), ("solaris", "solaris")],
                db_index=True,
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
        migrations.AlterField(
            model_name="pluginconfigtemplate",
            name="os",
            field=models.CharField(
                choices=[("windows", "windows"), ("linux", "linux"), ("aix", "aix"), ("solaris", "solaris")],
                default="linux",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="proccontrol",
            name="os",
            field=models.CharField(
                choices=[("windows", "windows"), ("linux", "linux"), ("aix", "aix"), ("solaris", "solaris")],
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
    ]
