# Generated by Django 3.2.4 on 2023-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0066_auto_20220906_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="gseplugindesc",
            name="auto_type",
            field=models.IntegerField(
                choices=[(0, "周期执行进程"), (1, "常驻进程"), (2, "单次执行进程")], default=1, verbose_name="托管类型"
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="bk_addressing",
            field=models.CharField(default="static", max_length=16, verbose_name="寻址方式"),
        ),
    ]
