# Generated by Django 3.2.4 on 2022-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0066_auto_20220906_1626"),
    ]

    operations = [
        migrations.CreateModel(
            name="GseAgentDesc",
            fields=[
                (
                    "package_name",
                    models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="Agent包"),
                ),
                ("cert_name", models.CharField(max_length=128, verbose_name="证书包名")),
                ("client_name", models.CharField(max_length=128, verbose_name="client 完整包名")),
                ("version", models.CharField(max_length=32, verbose_name="Agent版本号")),
                ("source", models.CharField(max_length=32, verbose_name="来源")),
                ("is_upgrade_package", models.BooleanField(default=False, verbose_name="是否属于升级包")),
                ("is_proxy_package", models.BooleanField(default=False, verbose_name="是否为Proxy包")),
                ("is_support_config_template", models.BooleanField(default=False, verbose_name="是否支持配置文件引用")),
                ("md5", models.CharField(max_length=128, verbose_name="Agent升级包md5")),
                ("description", models.TextField(verbose_name="安装包描述")),
                (
                    "os_type",
                    models.CharField(
                        choices=[("LINUX", "LINUX"), ("WINDOWS", "WINDOWS"), ("AIX", "AIX"), ("SOLARIS", "SOLARIS")],
                        db_index=True,
                        default="LINUX",
                        max_length=16,
                        verbose_name="操作系统",
                    ),
                ),
                (
                    "cpu_arch",
                    models.CharField(
                        choices=[
                            ("x86", "x86"),
                            ("x86_64", "x86_64"),
                            ("powerpc", "powerpc"),
                            ("aarch64", "aarch64"),
                            ("sparc", "sparc"),
                        ],
                        db_index=True,
                        default="x86_64",
                        max_length=16,
                        verbose_name="CPU架构",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("version", "package_name", "os_type", "cpu_arch", "md5", "is_upgrade_package", "is_proxy_package")
                },
            },
        ),
    ]
