# Generated by Django 3.2.4 on 2023-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0067_auto_20230201_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="gse_version",
            field=models.CharField(
                choices=[("V1", "V1"), ("V2", "V2")], default="V1", max_length=32, verbose_name="GSE 版本"
            ),
        ),
    ]
