# Generated by Django 3.2.4 on 2023-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0068_accesspoint_gse_version"),
        ("node_man", "0068_bk_addressing_migration"),
    ]

    operations = []
