# Generated by Django 3.2.4 on 2023-08-04 02:19

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('node_man', '0071_update_ap_gse_version_to_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='instance_selector',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='订阅任务范围主机属性筛选'),
        ),
    ]
