# Generated by Django 3.2.4 on 2023-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0076_auto_20230924_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="installchannel",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="是否隐藏"),
        ),
    ]
