# Generated by Django 3.2.4 on 2023-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0075_pluginconfigtemplate_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="from_system",
            field=models.CharField(db_index=True, default="", max_length=45, verbose_name="所属系统"),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.CharField(db_index=True, default="", max_length=45, verbose_name="操作人"),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="任务结束时间"),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("INSTALL_AGENT", "INSTALL_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("REINSTALL_AGENT", "REINSTALL_AGENT"),
                    ("UNINSTALL_AGENT", "UNINSTALL_AGENT"),
                    ("REMOVE_AGENT", "REMOVE_AGENT"),
                    ("UPGRADE_AGENT", "UPGRADE_AGENT"),
                    ("IMPORT_AGENT", "IMPORT_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("RELOAD_AGENT", "RELOAD_AGENT"),
                    ("ACTIVATE_AGENT", "ACTIVATE_AGENT"),
                    ("MAIN_START_PLUGIN", "MAIN_START_PLUGIN"),
                    ("MAIN_STOP_PLUGIN", "MAIN_STOP_PLUGIN"),
                    ("MAIN_RESTART_PLUGIN", "MAIN_RESTART_PLUGIN"),
                    ("MAIN_RELOAD_PLUGIN", "MAIN_RELOAD_PLUGIN"),
                    ("MAIN_DELEGATE_PLUGIN", "MAIN_DELEGATE_PLUGIN"),
                    ("MAIN_UNDELEGATE_PLUGIN", "MAIN_UNDELEGATE_PLUGIN"),
                    ("MAIN_INSTALL_PLUGIN", "MAIN_INSTALL_PLUGIN"),
                    ("MAIN_STOP_AND_DELETE_PLUGIN", "MAIN_STOP_AND_DELETE_PLUGIN"),
                    ("DEBUG_PLUGIN", "DEBUG_PLUGIN"),
                    ("STOP_DEBUG_PLUGIN", "STOP_DEBUG_PLUGIN"),
                    ("PUSH_CONFIG_PLUGIN", "PUSH_CONFIG_PLUGIN"),
                    ("REMOVE_CONFIG_PLUGIN", "REMOVE_CONFIG_PLUGIN"),
                    ("PACKING_PLUGIN", "PACKING_PLUGIN"),
                    ("INSTALL_PROXY", "INSTALL_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("REINSTALL_PROXY", "REINSTALL_PROXY"),
                    ("REPLACE_PROXY", "REPLACE_PROXY"),
                    ("UNINSTALL_PROXY", "UNINSTALL_PROXY"),
                    ("UPGRADE_PROXY", "UPGRADE_PROXY"),
                    ("IMPORT_PROXY", "IMPORT_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("RELOAD_PROXY", "RELOAD_PROXY"),
                ],
                db_index=True,
                default="INSTALL_PROXY",
                max_length=45,
                verbose_name="作业类型",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建任务时间"),
        ),
    ]
