# Generated by Django 3.2.4 on 2023-10-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0076_auto_20230924_2330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gseconfigtemplate",
            name="version",
            field=models.CharField(db_index=True, max_length=128, verbose_name="版本号"),
        ),
        migrations.AlterField(
            model_name="processstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "RUNNING"),
                    ("UNKNOWN", "UNKNOWN"),
                    ("TERMINATED", "TERMINATED"),
                    ("NOT_INSTALLED", "NOT_INSTALLED"),
                    ("UNREGISTER", "UNREGISTER"),
                    ("REMOVED", "REMOVED"),
                    ("MANUAL_STOP", "MANUAL_STOP"),
                    ("AGENT_NO_ALIVE", "AGENT_NO_ALIVE"),
                ],
                db_index=True,
                default="UNKNOWN",
                max_length=45,
                verbose_name="进程状态",
            ),
        ),
        migrations.AlterIndexTogether(
            name="gseconfigenv",
            index_together={("agent_name", "version")},
        ),
        migrations.AlterIndexTogether(
            name="gseconfigtemplate",
            index_together={("name", "version")},
        ),
        migrations.CreateModel(
            name="GseConfigExtraEnv",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("name", models.CharField(max_length=128, verbose_name="附加配置规则名称")),
                ("enable", models.BooleanField(default=True, verbose_name="是否启用")),
                ("condition", models.JSONField(verbose_name="灰度条件")),
                ("env_value", models.JSONField(verbose_name="环境变量值")),
            ],
            options={
                "verbose_name": "GSE 附加配置",
                "verbose_name_plural": "GSE 附加配置",
                "index_together": {("bk_biz_id", "enable")},
            },
        ),
    ]
