# Generated by Django 3.2.4 on 2023-11-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0077_auto_20231029_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="scope_id",
            field=models.IntegerField(db_index=True, null=True, verbose_name="订阅集合类型ID"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scope_type",
            field=models.CharField(
                choices=[("BIZ_SET", "业务集"), ("BIZ", "业务")],
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="订阅集合类型",
            ),
        ),
    ]
