# Generated by Django 3.2.4 on 2023-11-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_man', '0076_installchannel_hidden'),
        ('node_man', '0077_auto_20231029_1336'),
    ]

    operations = [
    ]
