# Generated by Django 3.2.4 on 2023-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0079_auto_20231114_2033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "等待执行"),
                    ("RUNNING", "正在执行"),
                    ("SUCCESS", "执行成功"),
                    ("FAILED", "执行失败"),
                    ("PART_FAILED", "部分失败"),
                    ("TERMINATED", "已终止"),
                    ("REMOVED", "已移除"),
                    ("FILTERED", "被过滤的"),
                    ("IGNORED", "已忽略"),
                ],
                db_index=True,
                default="PENDING",
                max_length=45,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="proccontrol",
            name="plugin_package_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="记录对应的插件包ID"),
        ),
        migrations.AlterIndexTogether(
            name="subscriptioninstancestatusdetail",
            index_together={("status", "create_time")},
        ),
    ]
