# Generated by Django 3.2.4 on 2024-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0080_auto_20231122_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gseconfigenv",
            name="os",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("aix", "aix"),
                    ("solaris", "solaris"),
                    ("darwin", "darwin"),
                ],
                db_index=True,
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
        migrations.AlterField(
            model_name="gseconfigtemplate",
            name="os",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("aix", "aix"),
                    ("solaris", "solaris"),
                    ("darwin", "darwin"),
                ],
                db_index=True,
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="os_type",
            field=models.CharField(
                choices=[
                    ("LINUX", "LINUX"),
                    ("WINDOWS", "WINDOWS"),
                    ("AIX", "AIX"),
                    ("SOLARIS", "SOLARIS"),
                    ("DARWIN", "DARWIN"),
                ],
                db_index=True,
                default="LINUX",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="os",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("aix", "aix"),
                    ("solaris", "solaris"),
                    ("darwin", "darwin"),
                ],
                db_index=True,
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
        migrations.AlterField(
            model_name="pluginconfigtemplate",
            name="os",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("aix", "aix"),
                    ("solaris", "solaris"),
                    ("darwin", "darwin"),
                ],
                default="linux",
                max_length=16,
                verbose_name="操作系统",
            ),
        ),
        migrations.AlterField(
            model_name="proccontrol",
            name="os",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("aix", "aix"),
                    ("solaris", "solaris"),
                    ("darwin", "darwin"),
                ],
                default="linux",
                max_length=32,
                verbose_name="系统类型",
            ),
        ),
    ]
