# Generated by Django 3.2.4 on 2024-09-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0082_gsepackagedesc_gsepackages"),
        ("node_man", "0082_host_dept_name"),
    ]

    operations = []
