# Generated by Django 3.2.4 on 2024-11-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0083_merge_20240911_1050"),
        ("node_man", "0083_subscription_operate_info"),
    ]

    operations = []
