# Generated by Django 3.2.4 on 2024-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_man', '0084_update_isp_and_accesspoint_regionid_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='node_type',
            field=models.CharField(choices=[('TOPO', '动态实例（拓扑）'), ('INSTANCE', '静态实例'), ('SERVICE_TEMPLATE', '服务模板'), ('SET_TEMPLATE', '集群模板'), ('DYNAMIC_GROUP', '动态分组')], db_index=True, max_length=20, verbose_name='节点类型'),
        ),
    ]
