# Generated by Django 3.2.4 on 2024-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0084_update_isp_and_accesspoint_regionid_cityid"),
    ]

    operations = [
        migrations.CreateModel(
            name="GsePackageDesc",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("project", models.CharField(db_index=True, max_length=32, unique=True, verbose_name="工程名")),
                ("description", models.TextField(verbose_name="安装包描述")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="英文插件描述")),
                (
                    "category",
                    models.CharField(
                        choices=[("official", "official"), ("external", "external"), ("scripts", "scripts")],
                        max_length=32,
                        verbose_name="所属范围",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gse包描述（GsePackageDesc）",
                "verbose_name_plural": "Gse包描述（GsePackageDesc）",
            },
        ),
        migrations.CreateModel(
            name="GsePackages",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("pkg_name", models.CharField(max_length=128, verbose_name="压缩包名")),
                ("version", models.CharField(max_length=128, verbose_name="版本号")),
                ("project", models.CharField(db_index=True, max_length=32, verbose_name="工程名")),
                ("pkg_size", models.IntegerField(verbose_name="包大小")),
                ("pkg_path", models.CharField(max_length=128, verbose_name="包路径")),
                ("md5", models.CharField(max_length=32, verbose_name="md5值")),
                ("location", models.CharField(max_length=512, verbose_name="安装包链接")),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("windows", "windows"),
                            ("linux", "linux"),
                            ("aix", "aix"),
                            ("solaris", "solaris"),
                            ("darwin", "darwin"),
                        ],
                        db_index=True,
                        default="linux",
                        max_length=32,
                        verbose_name="系统类型",
                    ),
                ),
                (
                    "cpu_arch",
                    models.CharField(
                        choices=[
                            ("x86", "x86"),
                            ("x86_64", "x86_64"),
                            ("powerpc", "powerpc"),
                            ("aarch64", "aarch64"),
                            ("sparc", "sparc"),
                        ],
                        db_index=True,
                        default="x86_64",
                        max_length=32,
                        verbose_name="CPU类型",
                    ),
                ),
                ("is_ready", models.BooleanField(default=True, verbose_name="插件是否可用")),
                ("version_log", models.TextField(blank=True, null=True, verbose_name="版本日志")),
                ("version_log_en", models.TextField(blank=True, null=True, verbose_name="英文版本日志")),
            ],
            options={
                "verbose_name": "Gse包（GsePackages）",
                "verbose_name_plural": "Gse包（GsePackages）",
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("INSTALL_AGENT", "INSTALL_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("REINSTALL_AGENT", "REINSTALL_AGENT"),
                    ("UNINSTALL_AGENT", "UNINSTALL_AGENT"),
                    ("REMOVE_AGENT", "REMOVE_AGENT"),
                    ("UPGRADE_AGENT", "UPGRADE_AGENT"),
                    ("DOWNGRADE_AGENT", "DOWNGRADE_AGENT"),
                    ("IMPORT_AGENT", "IMPORT_AGENT"),
                    ("RESTART_AGENT", "RESTART_AGENT"),
                    ("RELOAD_AGENT", "RELOAD_AGENT"),
                    ("ACTIVATE_AGENT", "ACTIVATE_AGENT"),
                    ("MAIN_START_PLUGIN", "MAIN_START_PLUGIN"),
                    ("MAIN_STOP_PLUGIN", "MAIN_STOP_PLUGIN"),
                    ("MAIN_RESTART_PLUGIN", "MAIN_RESTART_PLUGIN"),
                    ("MAIN_RELOAD_PLUGIN", "MAIN_RELOAD_PLUGIN"),
                    ("MAIN_DELEGATE_PLUGIN", "MAIN_DELEGATE_PLUGIN"),
                    ("MAIN_UNDELEGATE_PLUGIN", "MAIN_UNDELEGATE_PLUGIN"),
                    ("MAIN_INSTALL_PLUGIN", "MAIN_INSTALL_PLUGIN"),
                    ("MAIN_STOP_AND_DELETE_PLUGIN", "MAIN_STOP_AND_DELETE_PLUGIN"),
                    ("DEBUG_PLUGIN", "DEBUG_PLUGIN"),
                    ("STOP_DEBUG_PLUGIN", "STOP_DEBUG_PLUGIN"),
                    ("PUSH_CONFIG_PLUGIN", "PUSH_CONFIG_PLUGIN"),
                    ("REMOVE_CONFIG_PLUGIN", "REMOVE_CONFIG_PLUGIN"),
                    ("PACKING_PLUGIN", "PACKING_PLUGIN"),
                    ("INSTALL_PROXY", "INSTALL_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("REINSTALL_PROXY", "REINSTALL_PROXY"),
                    ("REPLACE_PROXY", "REPLACE_PROXY"),
                    ("UNINSTALL_PROXY", "UNINSTALL_PROXY"),
                    ("UPGRADE_PROXY", "UPGRADE_PROXY"),
                    ("IMPORT_PROXY", "IMPORT_PROXY"),
                    ("RESTART_PROXY", "RESTART_PROXY"),
                    ("RELOAD_PROXY", "RELOAD_PROXY"),
                ],
                db_index=True,
                default="INSTALL_PROXY",
                max_length=45,
                verbose_name="作业类型",
            ),
        ),
    ]
