# Generated by Django 4.2 on 2025-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0085_cloud_tenant_id_host_tenant_id_job_tenant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="tenant_id",
            field=models.CharField(
                blank=True, db_index=True, default="default", max_length=64, null=True, verbose_name="租户ID"
            ),
        ),
    ]
