# Generated by Django 3.2.4 on 2024-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0085_alter_subscription_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="is_use_sudo",
            field=models.BooleanField(default=True, verbose_name="是否使用sudo执行安装命令"),
        ),
    ]
