# Generated by Django 4.2 on 2025-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0085_cloud_tenant_id_host_tenant_id_job_tenant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BizEventDataIdMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("alarm_event_data_id", models.IntegerField(db_index=True, verbose_name="监控告警事件data_id")),
            ],
            options={
                "verbose_name": "业务告警事件data_id映射表",
                "verbose_name_plural": "业务告警事件data_id映射表",
            },
        ),
    ]
