# Generated by Django 4.2 on 2025-10-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_man", "0091_bizeventdataidmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="gseplugindesc",
            name="tenant_id",
            field=models.CharField(
                blank=True, db_index=True, default="default", max_length=64, null=True, verbose_name="租户ID"
            ),
        ),
        migrations.AddField(
            model_name="packages",
            name="tenant_id",
            field=models.CharField(
                blank=True, db_index=True, default="default", max_length=64, null=True, verbose_name="租户ID"
            ),
        ),
    ]
