# Generated by Django 2.2.6 on 2021-10-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSAKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="密钥名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("PUBLIC_KEY", "公钥"), ("PRIVATE_KEY", "私钥")], max_length=64, verbose_name="密钥类型"
                    ),
                ),
                ("description", models.TextField(default="", null=True, verbose_name="密钥描述")),
                ("content", models.TextField(verbose_name="密钥内容")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "RSA密钥",
                "verbose_name_plural": "RSA密钥",
                "unique_together": {("name", "type")},
            },
        ),
    ]
