# Generated by Django 3.2.4 on 2023-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encrypt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsymmetricKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="密钥名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("PUBLIC_KEY", "公钥"), ("PRIVATE_KEY", "私钥")], max_length=64, verbose_name="密钥类型"
                    ),
                ),
                ("cipher_type", models.CharField(default="RSA", max_length=64, verbose_name="加密类型")),
                ("description", models.TextField(default="", null=True, verbose_name="密钥描述")),
                ("content", models.TextField(verbose_name="密钥内容")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "非对称加密密钥",
                "verbose_name_plural": "非对称加密密钥",
                "unique_together": {("name", "type", "cipher_type")},
            },
        ),
        migrations.DeleteModel(
            name="RSAKey",
        ),
    ]
