# Generated by Django 3.2.4 on 2023-11-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encrypt", "0002_auto_20230712_1436"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="rsakey",
            index_together={("name", "type", "cipher_type")},
        ),
    ]
