# Generated by Django 2.2.6 on 2021-08-27 11:07

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BKJobFileSource",
            fields=[
                (
                    "credential_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="凭证ID"),
                ),
                ("file_source_id", models.IntegerField(db_index=True, verbose_name="文件源ID")),
                ("code", models.CharField(max_length=128, verbose_name="文件源标识")),
                ("alias", models.CharField(max_length=128, verbose_name="文件源别名")),
                ("access_params", django_mysql.models.JSONField(default=dict, verbose_name="文件源接入参数")),
                ("file_prefix", models.CharField(default="", max_length=128, verbose_name="文件源标识")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "作业平台文件源",
                "verbose_name_plural": "作业平台文件源",
            },
        ),
        migrations.CreateModel(
            name="BKJobFileCredential",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("storage_type", models.CharField(db_index=True, max_length=128, verbose_name="文件源存储类型")),
                ("name", models.CharField(max_length=128, verbose_name="凭证名称")),
                ("type", models.CharField(max_length=64, verbose_name="凭证类型")),
                ("description", models.TextField(default="", verbose_name="凭证描述")),
                ("credential_id", models.CharField(max_length=128, verbose_name="凭证ID")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "作业平台文件凭证",
                "verbose_name_plural": "作业平台文件凭证",
                "unique_together": {("bk_biz_id", "storage_type")},
            },
        ),
    ]
