# Generated by Django 3.2.4 on 2022-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TagChangeRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("tag_id", models.IntegerField(verbose_name="标签 ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("DELETE", "删除标签"), ("CREATE", "新建标签"), ("UPDATE", "更新版本"), ("OVERWRITE", "同版本覆盖更新")],
                        max_length=20,
                        verbose_name="变更动作",
                    ),
                ),
                ("target_version", models.CharField(max_length=128, verbose_name="指向版本号")),
            ],
            options={
                "verbose_name": "标签变更记录",
                "verbose_name_plural": "标签变更记录",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("updated_time", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, default="", max_length=32, verbose_name="修改者")),
                ("name", models.CharField(max_length=128, verbose_name="标签名称")),
                ("to_top", models.BooleanField(default=False, verbose_name="标签是否置顶")),
                ("description", models.TextField(default="", null=True, verbose_name="标签描述")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("PLUGIN", "插件"), ("AGENT", "Agent")], max_length=20, verbose_name="目标类型"
                    ),
                ),
                ("target_id", models.IntegerField(verbose_name="目标 ID")),
                ("target_version", models.CharField(max_length=128, verbose_name="指向版本号")),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "unique_together": {("target_type", "target_id", "name")},
            },
        ),
    ]
