# Generated by Django 3.2.4 on 2023-10-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_visiblerange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=128, verbose_name="标签名称"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="target_id",
            field=models.IntegerField(db_index=True, verbose_name="目标 ID"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="target_version",
            field=models.CharField(db_index=True, max_length=128, verbose_name="指向版本号"),
        ),
        migrations.AlterIndexTogether(
            name="tag",
            index_together={("target_id", "target_type")},
        ),
    ]
