# Generated by Django 3.2.4 on 2024-02-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20231029_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('target_type', 'target_id', 'name', 'target_version')},
        ),
    ]
