spec_version: 2

release:
  # 发布版本号
  version: 1.0.0
  title: "API 初始化"
  comment: "API 初始化"

# 定义网关基本信息，用于命令 `sync_apigw_config`
apigateway:
  description: "节点管理 API"
  # 网关的英文描述，蓝鲸官方网关需提供英文描述，以支持国际化
  description_en: "NodeMan API"
  is_public: true
  api_type: 1
  maintainers:
    - "admin"

# 定义环境信息，用于命令 `sync_apigw_stage`
stages:
  - name: "{{ settings.ENVIRONMENT }}"
{% if settings.ENVIRONMENT == "prod" %}
    description: "正式环境"
    description_en: "Prod"
{% elif settings.ENVIRONMENT == "stag" %}
    description: "预发布环境"
    description_en: "Test"
{% else %}
    description: "开发测试环境"
    description_en: "Development"
{% endif %}
    backends:
      - name: "default"
        config:
          timeout: 180
          loadbalance: "roundrobin"
          hosts:
          # 网关调用后端服务的默认域名或IP，不包含Path，比如：      http://api.example.com
            - host: "{{ settings.BK_NODEMAN_BACKEND_HOST }}"
              weight: 100

grant_permissions:
  - bk_app_code: "bk_sops"
    grant_dimension: "resource"
    resource_names:
      - system_ap_list
      - system_cloud_list
      - system_fetch_public_keys
      - system_install_channel_list
      - system_ipchooser_host_details
      - system_job_details
      - system_job_install
      - system_job_operate
      - system_list_packages
      - system_get_job_log
      - system_search_host_plugin
      - system_operate_plugin
      - system_plugin_list
  - bk_app_code: "bk_dataweb"
    grant_dimension: "resource"
    resource_names:
      - system_ipchooser_host_details
  - bk_app_code: "bk_bkdata"
    grant_dimension: "resource"
    resource_names:
      - system_subscription_create
      - system_subscription_update
      - system_subscription_info
      - system_subscription_run
      - system_subscription_switch
      - system_subscription_instance_status
      - system_subscription_task_result
      - system_subscription_delete
      - system_subscription_task_result_detail
      - system_list_hosts
      - system_search_host_plugin
  - bk_app_code: "bk_bcs_app"
    grant_dimension: "resource"
    resource_names:
      - system_cloud_list
      - system_job_install
      - system_job_details
      - system_list_hosts
  - bk_app_code: "bk_monitorv3"
    grant_dimension: "resource"
    resource_names:
      - system_plugin_render_config_template
      - system_plugin_start_debug
      - system_plugin_query_debug
      - system_plugin_stop_debug
      - system_plugin_upload
      - system_plugin_create_register_task
      - system_plugin_query_register_task
      - system_plugin_info
      - system_plugin_create_config_template
      - system_plugin_release
      - system_plugin_release_config_template
      - system_plugin_create_export_task
      - system_plugin_query_export_task
      - system_plugin_delete
      - system_subscription_create
      - system_subscription_info
      - system_subscription_update
      - system_subscription_delete
      - system_subscription_run
      - system_subscription_retry
      - system_subscription_revoke
      - system_subscription_task_result
      - system_subscription_switch
      - system_subscription_instance_status
      - system_subscription_task_result_detail
      - system_list_cloud_proxies
      - system_list_biz_proxies
      - system_operate_plugin
      - system_search_host_plugin
      - system_subscription_check_task_ready
      - system_subscription_statistic
      - system_ipchooser_host_details

resource_docs:
  # 资源文档的归档文件，可为 tar.gz，zip 格式文件；创建归档文件可使用指令 `tar czvf xxx.tgz en zh`
  # archivefile: "{{ settings.BK_APIGW_RESOURCE_DOCS_ARCHIVE_FILE }}"
  # 资源文档目录，basedir 与 archivefile 二者至少一个有效，若同时存在，则 archivefile 优先
  # basedir: "{{ settings.BK_APIGW_RESOURCE_DOCS_BASE_DIR }}"
  basedir: "support-files/apigw/apidocs"


