spec_version: 2

release:
  # 发布版本号
  version: 1.0.0
  title: "API 初始化"
  comment: "API 初始化"

# 定义网关基本信息，用于命令 `sync_apigw_config`
apigateway:
  description: "节点管理 API"
  # 网关的英文描述，蓝鲸官方网关需提供英文描述，以支持国际化
  description_en: "NodeMan API"
  is_public: true
  api_type: 1
  maintainers:
    - "admin"

# 定义环境信息，用于命令 `sync_apigw_stage`
stages:
  - name: "{{ settings.ENVIRONMENT }}"
{% if settings.ENVIRONMENT == "prod" %}
    description: "正式环境"
    description_en: "Prod"
{% elif settings.ENVIRONMENT == "stag" %}
    description: "预发布环境"
    description_en: "Test"
{% else %}
    description: "开发测试环境"
    description_en: "Development"
{% endif %}
    backends:
      - name: "default"
        config:
          timeout: 180
          loadbalance: "roundrobin"
          hosts:
          # 网关调用后端服务的默认域名或IP，不包含Path，比如：      http://api.example.com
            - host: "{{ settings.BK_NODEMAN_BACKEND_HOST }}"
              weight: 100

grant_permissions:
  - bk_app_code: {{ settings.APP_CODE }}
    grant_dimension: "gateway"
  # bk_sops
  - bk_app_code: bk_sops
    grant_dimension: "resource"
    resource_names:
      - system_ap_list_ap
      - system_cloud_list_cloud
      - system_rsa_fetch_public_keys
      - system_installchannel_list_install_channel
      - system_ipchooser_host_details
      - system_job_retrieve_job
      - system_job_install_job
      - system_job_operate_job
      - system_plugin_list_package
      - system_job_get_job_log
      - system_plugin_list_host
      - system_plugin_operate_plugin
      - system_plugin_v2_operate_plugin
      - system_plugin_list_host
  # bk_dataweb
  - bk_app_code: bk_dataweb
    grant_dimension: "resource"
    resource_names:
      - system_ipchooser_host_details
  # bk_bkdata
  - bk_app_code: bk_bkdata
    grant_dimension: "resource"
    resource_names:
      - system_subscription_create_subscription
      - system_subscription_update_subscription
      - system_subscription_subscription_info
      - system_subscription_run_subscription
      - system_subscription_subscription_switch
      - system_subscription_query_instance_status
      - system_subscription_subscription_task_result
      - system_subscription_delete_subscription
      - system_subscription_subscription_task_result_detail
      - system_host_list_host
      - system_plugin_list_host
      - system_ipchooser_host_details
  # bk_bcs_app
  - bk_app_code: bk_bcs_app
    grant_dimension: "resource"
    resource_names:
      - system_cloud_list_cloud
      - system_job_retrieve_job
      - system_job_install_job
      - system_host_list_host
      - cloud_list_cloud
      - job_retrieve_job
      - job_install_job
      - host_list_host
  # bk_monitorv3
  - bk_app_code: bk_monitorv3
    grant_dimension: "resource"
    resource_names:
      - system_backend_plugin_render_plugin_config_template
      - system_backend_plugin_start_debug
      - system_backend_plugin_query_debug
      - system_backend_plugin_stop_debug
      - system_backend_plugin_upload
      - system_backend_plugin_create_register_task
      - system_backend_plugin_query_register_task
      - system_backend_plugin_query_plugin_info
      - system_backend_plugin_create_plugin_config_template
      - system_backend_plugin_release_package
      - system_backend_plugin_release_plugin_config_template
      - system_plugin_v2_create_export_plugin_task
      - system_plugin_v2_query_export_plugin_task
      - system_backend_plugin_delete_plugin
      - system_subscription_create_subscription
      - system_subscription_subscription_info
      - system_subscription_update_subscription
      - system_subscription_delete_subscription
      - system_subscription_run_subscription
      - system_subscription_retry_subscription
      - system_subscription_revoke_subscription
      - system_subscription_subscription_task_result
      - system_subscription_subscription_switch
      - system_subscription_query_instance_status
      - system_subscription_subscription_task_result_detail
      - system_host_retrieve_cloud_proxies
      - system_host_retrieve_biz_proxies
      - system_plugin_operate_plugin
      - system_plugin_list_host
      - system_subscription_subscription_check_task_ready
      - system_subscription_statistic
      - system_ipchooser_host_details
  # bk_log_search
  - bk_app_code: bk_log_search
    grant_dimension: "resource"
    resource_names:
      - system_subscription_create_subscription
      - system_subscription_update_subscription
      - system_subscription_subscription_info
      - system_subscription_run_subscription
      - system_subscription_query_instance_status
      - system_subscription_subscription_task_result
      - system_plugin_list_host
      - system_subscription_subscription_check_task_ready
      - system_subscription_delete_subscription
      - system_subscription_subscription_task_result_detail
      - system_subscription_subscription_switch
      - system_subscription_statistic
      - system_subscription_query_host_subscription_ids
      - system_subscription_retry_subscription
      - system_ipchooser_host_details
      - system_host_retrieve_biz_proxies
  - bk_app_code: bk_dbm
    grant_dimension: "resource"
    resource_names:
      - system_plugin_operate_plugin
      - system_job_retrieve_job
      - system_ipchooser_host_details

resource_docs:
  # 资源文档的归档文件，可为 tar.gz，zip 格式文件；创建归档文件可使用指令 `tar czvf xxx.tgz en zh`
  # archivefile: "{{ settings.BK_APIGW_RESOURCE_DOCS_ARCHIVE_FILE }}"
  # 资源文档目录，basedir 与 archivefile 二者至少一个有效，若同时存在，则 archivefile 优先
  # basedir: "{{ settings.BK_APIGW_RESOURCE_DOCS_BASE_DIR }}"
  basedir: "support-files/apigw/apidocs"


