# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Start New Version

on:
  push:
    branches:
      - V[0-9]+.[0-9]+.X

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Start New Version
      run: |
        pip install PyYAML
        eval $(./scripts/parse_app_yml.sh app.yml "yml_")
        echo current_version:${yml_version}
        python scripts/extract_version_log.py ${yml_version}
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "github-actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add .
        git commit -m "docs: auto generate version log"
        git push
        git tag -a V${yml_version} -m "$(cat release/V${yml_version}*)"
        git push origin V${yml_version}
        echo next_version:${yml_next_version}
        sed -ie "s/version: ${yml_version}/version: ${yml_next_version}/" app.yml
        mkdir -p dev_log/${yml_next_version}
        touch dev_log/${yml_next_version}/.gitkeep
        git add .
        git commit -m "minor: start new version ${yml_next_version}"
        git branch V${yml_next_version}rc
        git checkout V${yml_next_version}rc
        git push --set-upstream origin V${yml_next_version}rc
